### PR TITLE
Multiple language fields

### PR DESCRIPTION
**Pull request by woodkri**
Addresses issues #56, #350, #352, #349

### CODE REVIEW

**Comment by eddavies** [comment]
Also (somewhat minor) some of the data fields are not positioned directly under one another: 
minor push other field right

Either fields with "+" should be moved to the left or other fields moved slightly right.

**Comment by woodkri** [comment]
@eddavies All of the language fields are autocompletes, are none of them working for you? You have to type in two letters before anything will pop up, it's too slow otherwise.

I didn't realize there were fields that opened up the concept editor from the competencies until just now. I did have to make a change for them to display properly but I didn't have any trouble selecting or adding. When you select a concept and click add, nothing happens?

**Comment by eddavies** [comment]
Yes to both.
I can select concepts, but the add button doesn't do anything for me. 

Could I have done something incorrectly on my end when testing locally? I'm not sure what.

**Comment by woodkri** [comment]
@eddavies I shifted the input boxes to the right to align with the fields that allow multiple entries. When I tried moving those to the left it looked bad when adding another entry because the X is to the left of subsequent entries. Let me know what you think. An alternative would be to move the X next to the + so that all the input fields would be aligned to the left.

**Comment by eddavies** [comment]
Okay, after properly setting up the server, the autocomplete is working, the ability to add concepts does work, and the back button on the concept screen works. So it definitely was on my end.

I think the way the boxes are aligned look good.

@lomilar I believe this is good to go. I haven't found any major errors with this.

**Comment by Lomilar** [comment]
I'd like to freeze this pull request until after we do our end of year 0.4 release, because no other tools would probably survive the sudden internationalization of a whole bunch of fields.

Feel free to merge it to an 0.5 branch in cass-editor or just wait until after the end of year.

Great work!

**Comment by Lomilar** [comment]
Did a review with @siuc-nate 
* Needs default language: Framework Language > Browser Language > en
* Needs show the language instead of the lang code (similar to inLanguage)

**Comment by Lomilar** [comment]
All fields please.

**Comment by woodkri** [comment]
Branch is ready for merge/testing.

**Pull request merged**
